# Pega tu URL de Supabase de la Fase 1
SUPABASE_URL = "https://iywapkdxoqvnzityxrwr.supabase.co"

# Pega tu clave API (anon key) de Supabase de la Fase 1
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5d2Fwa2R4b3F2bnppdHl4cndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2ODQyODcsImV4cCI6MjA3NzI2MDI4N30.Y6ULElfjC5kMaDL9Ece5caQpFbJChInKHxFThms3i0k"

# URLs de los webhooks de n8n
N8N_WEBHOOK_URL = "http://localhost:5678/webhook/webhook-enrollment"
N8N_ENROLLMENT_WEBHOOK = "http://localhost:5678/webhook/webhook-enrollment"
N8N_WEBHOOK_PAYMENT = "http://localhost:5678/webhook/webhook-payment"
N8N_WEBHOOK_VERIFICATION = "http://localhost:5678/webhook/f414fca8-cbc4-4d4a-ae86-74c21d4b7ea4/verify-certificate/:code"

JWT_SECRET = "clave-temporal"